spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        create_empty_composites:
          enabled: true
        format_sql: true
        default_batch_fetch_size: 100
  task:
    execution:
      pool:
        core-size: 2
        max-size: 10
        queue-capacity: 20

security.jwt.token:
  secret-key: testtesttesttesttesttesttesttesttestttttest
  expire-length: 1800000

springdoc:
  default-consumes-media-type: application/json
  default-produces-media-type: application/json
  swagger-ui:
    path: /swagger-ui.html
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha
    tags-sorter: alpha
